# Use postgres/example user/password credentials
# copied from https://hub.docker.com/_/postgres
version: '3.1'

services:

  db:
    build: .
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgresdata:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - '5432:5432'

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  postgresdata:
    driver: local